name: Advent of Code 2024

on:
  push:
    branches:
      - master
    paths:
      - "advent-of-code-2024/**"
      - ".github/**"

  workflow_dispatch:

defaults:
  run:
    working-directory: "advent-of-code-2024"

jobs:
  aoc-2024-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
