# Runs linter and tests on Advent of Code 2020 files

name: Advent of Code 2020

on:
  push:
    branches:
      - master
    paths:
      - "advent-of-code-2020/**"
      - ".github/**"

  workflow_dispatch:

defaults:
  run:
    working-directory: "advent-of-code-2020"

jobs:
  aoc-2020-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.6"

      - name: Install dependencies
        run: pip install flake8 pytest

      - name: Lint with flake8
        run: flake8 . --count --show-source --statistics

      - name: Test
        run: pytest
