# Runs linter and tests on Advent of Code 2021 files

name: Advent of Code 2021

on:
  push:
    branches:
      - master
    paths:
      - "advent-of-code-2021/"
      - ".github/"

  workflow_dispatch:

defaults:
  run:
    working-directory: "advent-of-code-2021"

jobs:
  aoc-2021-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.2"

      - name: StaticCheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          install-go: false

      - name: Lint
        run: "go vet ./..."

      - name: Test
        run: "go test ./..."
